"""team_tasks_customer_supply_order_fks

Revision ID: 0cbf55175cf2
Revises: d55b52344beb
Create Date: 2026-05-24 02:39:15.930707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cbf55175cf2'
down_revision: Union[str, Sequence[str], None] = 'd55b52344beb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('supply_order_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_team_tasks_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_tasks_supply_order_id'), ['supply_order_id'], unique=False)
        batch_op.create_foreign_key('fk_team_tasks_customer_id', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_team_tasks_supply_order_id', 'supply_orders', ['supply_order_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_team_tasks_supply_order_id', type_='foreignkey')
        batch_op.drop_constraint('fk_team_tasks_customer_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_team_tasks_supply_order_id'))
        batch_op.drop_index(batch_op.f('ix_team_tasks_customer_id'))
        batch_op.drop_column('supply_order_id')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
