"""cashbook_tables

Revision ID: 2ca9e4ef1c34
Revises: 80d9aa60498c
Create Date: 2026-05-23 19:35:08.339058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca9e4ef1c34'
down_revision: Union[str, Sequence[str], None] = '80d9aa60498c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('account_type', sa.String(length=16), server_default='cash', nullable=False),
    sa.Column('currency', sa.String(length=8), server_default='TRY', nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_cash_accounts_tenant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_accounts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cash_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('sales_record_id', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['cash_accounts.id'], name='fk_cash_transactions_account_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_record_id'], ['sales_records.id'], name='fk_cash_transactions_sales_record_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_cash_transactions_tenant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_transactions_sales_record_id'), ['sales_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_transactions_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_transactions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cash_transactions_sales_record_id'))
        batch_op.drop_index(batch_op.f('ix_cash_transactions_account_id'))

    op.drop_table('cash_transactions')
    with op.batch_alter_table('cash_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_accounts_tenant_id'))

    op.drop_table('cash_accounts')
    # ### end Alembic commands ###
