"""user role_kind job_role_id

Revision ID: 3c5bc294dbf8
Revises: 93cdd8283926
Create Date: 2026-05-23 18:46:52.860921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5bc294dbf8'
down_revision: Union[str, Sequence[str], None] = '93cdd8283926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_kind', sa.String(length=16), server_default='staff', nullable=False))
        batch_op.add_column(sa.Column('job_role_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_job_role_id'), ['job_role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role_kind'), ['role_kind'], unique=False)
        batch_op.create_foreign_key('fk_users_job_role_id', 'job_role_templates', ['job_role_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###

    # --- data migration ---
    # Managers and admins become 'owner'; employees stay 'staff' (server_default).
    op.execute("UPDATE users SET role_kind = 'owner' WHERE role IN ('admin', 'manager')")

    # Wire existing employees to the per-tenant 'Kasiyer' system role.
    op.execute(
        """
        UPDATE users
        SET job_role_id = (
            SELECT id FROM job_role_templates
            WHERE tenant_id = users.tenant_id
              AND name = 'Kasiyer'
              AND is_system = 1
            LIMIT 1
        )
        WHERE role = 'employee'
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_job_role_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_role_kind'))
        batch_op.drop_index(batch_op.f('ix_users_job_role_id'))
        batch_op.drop_column('job_role_id')
        batch_op.drop_column('role_kind')

    # ### end Alembic commands ###
