"""sales_item_tax_rate_amount_product_tax_rate

Revision ID: 3e4ac0f2b66d
Revises: 0cbf55175cf2
Create Date: 2026-05-24 02:48:40.916941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4ac0f2b66d'
down_revision: Union[str, Sequence[str], None] = '0cbf55175cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default='20.00', nullable=False))

    with op.batch_alter_table('sales_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default='20.00', nullable=False))
        batch_op.add_column(sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_items', schema=None) as batch_op:
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('tax_rate')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('tax_rate')

    # ### end Alembic commands ###
