"""tenant_company_profile_fields

Revision ID: 3fdd450d45ad
Revises: ff8c38eb4b2b
Create Date: 2026-05-24 13:40:20.795785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fdd450d45ad'
down_revision: Union[str, Sequence[str], None] = 'ff8c38eb4b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('tax_number', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('bank_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('logo_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('logo_url')
        batch_op.drop_column('bank_info')
        batch_op.drop_column('tax_number')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
