"""security_hardening_phase_a

Revision ID: 69c63ee3b6d1
Revises: c3d4e5f6a7b8
Create Date: 2026-05-13 18:19:12.316407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c63ee3b6d1'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_tenant_sku'))
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=False)
        batch_op.create_unique_constraint('uq_products_tenant_sku', ['tenant_id', 'sku'])

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_at', sa.DateTime(timezone=True), nullable=True))

    # SQLite isimsiz FK constraint'i drop edemez — tablo yeniden oluşturularak CASCADE eklenir.
    with op.batch_alter_table('sales_items', schema=None, recreate='always') as batch_op:
        batch_op.create_foreign_key('fk_sales_items_product_id', 'products', ['product_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_records_tenant_record_no'))
        batch_op.create_index(batch_op.f('ix_sales_records_record_no'), ['record_no'], unique=False)
        batch_op.create_unique_constraint('uq_sales_records_tenant_record_no', ['tenant_id', 'record_no'])

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sales_records_tenant_record_no', type_='unique')
        batch_op.drop_index(batch_op.f('ix_sales_records_record_no'))
        batch_op.create_index(batch_op.f('ix_sales_records_tenant_record_no'), ['tenant_id', 'record_no'], unique=1)

    with op.batch_alter_table('sales_items', schema=None, recreate='always') as batch_op:
        batch_op.drop_constraint('fk_sales_items_product_id', type_='foreignkey')

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_column('used_at')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('uq_products_tenant_sku', type_='unique')
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.create_index(batch_op.f('ix_products_tenant_sku'), ['tenant_id', 'sku'], unique=1)

    # ### end Alembic commands ###
