"""initial schema

Revision ID: 70e4ca5f7a10
Revises: 
Create Date: 2026-05-02 21:02:00.137459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e4ca5f7a10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('stock_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reorder_level', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=True)

    op.create_table('sales_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_no', sa.String(length=64), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_records_record_no'), ['record_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_sales_records_sale_date'), ['sale_date'], unique=False)

    op.create_table('sales_forecast_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('forecast_start', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('result_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_forecast_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_forecast_results_forecast_start'), ['forecast_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_forecast_results_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_forecast_results_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_forecast_results_scope'), ['scope'], unique=False)

    op.create_table('sales_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_record_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_record_id'], ['sales_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_items_sales_record_id'), ['sales_record_id'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=16), nullable=False),
    sa.Column('change', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_product_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_movement_type'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_created_at'))

    op.drop_table('stock_movements')
    with op.batch_alter_table('sales_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_items_sales_record_id'))
        batch_op.drop_index(batch_op.f('ix_sales_items_product_id'))

    op.drop_table('sales_items')
    with op.batch_alter_table('sales_forecast_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_forecast_results_scope'))
        batch_op.drop_index(batch_op.f('ix_sales_forecast_results_product_id'))
        batch_op.drop_index(batch_op.f('ix_sales_forecast_results_model_name'))
        batch_op.drop_index(batch_op.f('ix_sales_forecast_results_forecast_start'))

    op.drop_table('sales_forecast_results')
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_records_sale_date'))
        batch_op.drop_index(batch_op.f('ix_sales_records_record_no'))

    op.drop_table('sales_records')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_category'))

    op.drop_table('products')
    # ### end Alembic commands ###
