"""add_record_comments_and_tags

Revision ID: 7afdfc50ada7
Revises: 3fdd450d45ad
Create Date: 2026-05-25 23:21:52.922800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7afdfc50ada7'
down_revision: Union[str, Sequence[str], None] = '3fdd450d45ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=150), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('record_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_record_comments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_comments_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('record_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'entity_type', 'entity_id', 'tag', name='uq_record_tag')
    )
    with op.batch_alter_table('record_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_record_tags_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_tags_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_record_tags_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_record_tags_id'))

    op.drop_table('record_tags')
    with op.batch_alter_table('record_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_record_comments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_record_comments_id'))

    op.drop_table('record_comments')
    # ### end Alembic commands ###
