"""sales_record created_by_user_id

Revision ID: 80d9aa60498c
Revises: 3c5bc294dbf8
Create Date: 2026-05-23 19:08:53.952199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d9aa60498c'
down_revision: Union[str, Sequence[str], None] = '3c5bc294dbf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_records_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_foreign_key('fk_sales_records_created_by_user_id', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sales_records_created_by_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_records_created_by_user_id'))
        batch_op.drop_column('created_by_user_id')

    # ### end Alembic commands ###
