"""stock_counts_table

Revision ID: 82414f9e582f
Revises: b06e1f90c215
Create Date: 2026-05-24 13:05:25.152843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82414f9e582f'
down_revision: Union[str, Sequence[str], None] = 'b06e1f90c215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('count_no', sa.String(length=64), nullable=False),
    sa.Column('count_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_stock_counts_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_stock_counts_tenant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_counts_count_date'), ['count_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_counts_count_no'), ['count_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_counts_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_counts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_counts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('stock_count_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('stock_count_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('system_qty', sa.Integer(), nullable=False),
    sa.Column('counted_qty', sa.Integer(), nullable=False),
    sa.Column('difference', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_stock_count_items_product_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_count_id'], ['stock_counts.id'], name='fk_stock_count_items_count_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_stock_count_items_tenant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_count_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_count_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_count_items_stock_count_id'), ['stock_count_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_count_items_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_count_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_count_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_stock_count_items_stock_count_id'))
        batch_op.drop_index(batch_op.f('ix_stock_count_items_product_id'))

    op.drop_table('stock_count_items')
    with op.batch_alter_table('stock_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_counts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_stock_counts_status'))
        batch_op.drop_index(batch_op.f('ix_stock_counts_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_stock_counts_count_no'))
        batch_op.drop_index(batch_op.f('ix_stock_counts_count_date'))

    op.drop_table('stock_counts')
    # ### end Alembic commands ###
