"""customer_orders_delivery_notes_invoices

Revision ID: b06e1f90c215
Revises: 3e4ac0f2b66d
Create Date: 2026-05-24 03:02:16.688113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06e1f90c215'
down_revision: Union[str, Sequence[str], None] = '3e4ac0f2b66d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_customer_orders_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_customer_orders_customer_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_customer_orders_tenant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_orders_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_orders_order_date'), ['order_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_orders_order_no'), ['order_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_orders_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('customer_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['customer_orders.id'], name='fk_customer_order_items_order_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_customer_order_items_product_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_customer_order_items_tenant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_order_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_order_items_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('delivery_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('delivery_no', sa.String(length=64), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_delivery_notes_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['customer_orders.id'], name='fk_delivery_notes_order_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_delivery_notes_tenant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_notes_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_notes_delivery_date'), ['delivery_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_notes_delivery_no'), ['delivery_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_notes_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_notes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_notes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('delivery_note_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('delivery_note_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_note_id'], ['delivery_notes.id'], name='fk_delivery_note_items_dn_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['customer_order_items.id'], name='fk_delivery_note_items_order_item_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_delivery_note_items_product_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_delivery_note_items_tenant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_note_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_note_items_delivery_note_id'), ['delivery_note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_note_items_order_item_id'), ['order_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_note_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_note_items_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('delivery_note_id', sa.Integer(), nullable=True),
    sa.Column('invoice_no', sa.String(length=64), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_invoices_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_invoices_customer_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delivery_note_id'], ['delivery_notes.id'], name='fk_invoices_delivery_note_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['customer_orders.id'], name='fk_invoices_order_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_invoices_tenant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_delivery_note_id'), ['delivery_note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_date'), ['invoice_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_no'), ['invoice_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_invoices_order_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_no'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_date'))
        batch_op.drop_index(batch_op.f('ix_invoices_delivery_note_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_customer_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_created_by_user_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('delivery_note_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_note_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_note_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_note_items_order_item_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_note_items_delivery_note_id'))

    op.drop_table('delivery_note_items')
    with op.batch_alter_table('delivery_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_notes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_notes_status'))
        batch_op.drop_index(batch_op.f('ix_delivery_notes_order_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_notes_delivery_no'))
        batch_op.drop_index(batch_op.f('ix_delivery_notes_delivery_date'))
        batch_op.drop_index(batch_op.f('ix_delivery_notes_created_by_user_id'))

    op.drop_table('delivery_notes')
    with op.batch_alter_table('customer_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_order_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_customer_order_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_customer_order_items_order_id'))

    op.drop_table('customer_order_items')
    with op.batch_alter_table('customer_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_orders_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_customer_orders_status'))
        batch_op.drop_index(batch_op.f('ix_customer_orders_order_no'))
        batch_op.drop_index(batch_op.f('ix_customer_orders_order_date'))
        batch_op.drop_index(batch_op.f('ix_customer_orders_customer_id'))
        batch_op.drop_index(batch_op.f('ix_customer_orders_created_by_user_id'))

    op.drop_table('customer_orders')
    # ### end Alembic commands ###
