"""team_tasks table

Revision ID: d55b52344beb
Revises: faf116cdef10
Create Date: 2026-05-24 02:06:19.902244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd55b52344beb'
down_revision: Union[str, Sequence[str], None] = 'faf116cdef10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name='fk_team_tasks_assignee_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_team_tasks_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_team_tasks_tenant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_tasks_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_tasks_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_tasks_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_tasks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_team_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_team_tasks_due_date'))
        batch_op.drop_index(batch_op.f('ix_team_tasks_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_tasks_assignee_id'))

    op.drop_table('team_tasks')
    # ### end Alembic commands ###
