"""account_movements table

Revision ID: faf116cdef10
Revises: 2ca9e4ef1c34
Create Date: 2026-05-24 01:35:01.533747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf116cdef10'
down_revision: Union[str, Sequence[str], None] = '2ca9e4ef1c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('sales_record_id', sa.Integer(), nullable=True),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_account_movements_customer_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_record_id'], ['sales_records.id'], name='fk_account_movements_sales_record_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_account_movements_tenant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_movements_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_movements_movement_date'), ['movement_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_movements_sales_record_id'), ['sales_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_movements_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_movements_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_account_movements_sales_record_id'))
        batch_op.drop_index(batch_op.f('ix_account_movements_movement_date'))
        batch_op.drop_index(batch_op.f('ix_account_movements_customer_id'))

    op.drop_table('account_movements')
    # ### end Alembic commands ###
