"""sales_item_cost_price_snapshot

Revision ID: ff8c38eb4b2b
Revises: 82414f9e582f
Create Date: 2026-05-24 13:13:48.265190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8c38eb4b2b'
down_revision: Union[str, Sequence[str], None] = '82414f9e582f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_price_snapshot', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_items', schema=None) as batch_op:
        batch_op.drop_column('cost_price_snapshot')

    # ### end Alembic commands ###
